[package]
name = "hashing"
type = "lib"
authors = [""]

[dependencies]
trees = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "main", directory = "packages/merkle-trees" }
constants = { path = "../constants" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }